
package org.acmemobility.station_wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2026-06-24T20:51:47.334+02:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "HardwareErrorFaultType", targetNamespace = "http://acmemobility.org/station.xsd")
public class HardwareErrorFaultType extends Exception {

    private org.acmemobility.station.HardwareErrorFaultType faultInfo;

    public HardwareErrorFaultType() {
        super();
    }

    public HardwareErrorFaultType(String message) {
        super(message);
    }

    public HardwareErrorFaultType(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public HardwareErrorFaultType(String message, org.acmemobility.station.HardwareErrorFaultType hardwareErrorFaultType) {
        super(message);
        this.faultInfo = hardwareErrorFaultType;
    }

    public HardwareErrorFaultType(String message, org.acmemobility.station.HardwareErrorFaultType hardwareErrorFaultType, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = hardwareErrorFaultType;
    }

    public org.acmemobility.station.HardwareErrorFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
