
package org.acmemobility.station_wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2026-06-24T20:51:47.350+02:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "InvalidRequestFaultType", targetNamespace = "http://acmemobility.org/station.xsd")
public class InvalidRequestFaultType extends Exception {

    private org.acmemobility.station.InvalidRequestFaultType faultInfo;

    public InvalidRequestFaultType() {
        super();
    }

    public InvalidRequestFaultType(String message) {
        super(message);
    }

    public InvalidRequestFaultType(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidRequestFaultType(String message, org.acmemobility.station.InvalidRequestFaultType invalidRequestFaultType) {
        super(message);
        this.faultInfo = invalidRequestFaultType;
    }

    public InvalidRequestFaultType(String message, org.acmemobility.station.InvalidRequestFaultType invalidRequestFaultType, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidRequestFaultType;
    }

    public org.acmemobility.station.InvalidRequestFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
