package org.acmemobility.station_wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2026-06-24T20:51:47.364+02:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://acmemobility.org/station.wsdl", name = "StationPort")
@XmlSeeAlso({org.acmemobility.station.ObjectFactory.class})
public interface StationPort {

    @WebMethod(action = "lock")
    @RequestWrapper(localName = "lock", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.Lock")
    @ResponseWrapper(localName = "lockResponse", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.LockResponse")
    public void lock(

        @WebParam(name = "vehicleId", targetNamespace = "")
        java.lang.String vehicleId,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "stationId", targetNamespace = "")
        java.lang.String stationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "finalBatteryLevel", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.Double> finalBatteryLevel,
        @WebParam(mode = WebParam.Mode.OUT, name = "success", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.Boolean> success,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.String> message
    ) throws StationNotExistsFaultType, HardwareErrorFaultType, VehicleNotFoundFaultType, InvalidRequestFaultType;

    @WebMethod(action = "reserve")
    @RequestWrapper(localName = "reserve", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.Reserve")
    @ResponseWrapper(localName = "reserveResponse", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.ReserveResponse")
    public void reserve(

        @WebParam(name = "vehicleId", targetNamespace = "")
        java.lang.String vehicleId,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "stationId", targetNamespace = "")
        java.lang.String stationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "success", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.Boolean> success,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.String> message
    ) throws StationNotExistsFaultType, VehicleNotFoundFaultType, VehicleNotAvailableFaultType;

    @WebMethod(action = "getAllStations")
    @RequestWrapper(localName = "getAllStations", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.GetAllStations")
    @ResponseWrapper(localName = "getAllStationsResponse", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.GetAllStationsResponse")
    @WebResult(name = "stations", targetNamespace = "")
    public java.util.List<org.acmemobility.station.StationInfo> getAllStations()
;

    @WebMethod(action = "unlock")
    @RequestWrapper(localName = "unlock", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.Unlock")
    @ResponseWrapper(localName = "unlockResponse", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.UnlockResponse")
    public void unlock(

        @WebParam(name = "vehicleId", targetNamespace = "")
        java.lang.String vehicleId,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "stationId", targetNamespace = "")
        java.lang.String stationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "success", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.Boolean> success,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.String> message
    ) throws StationNotExistsFaultType, HardwareErrorFaultType, VehicleNotFoundFaultType, InvalidRequestFaultType, VehicleNotAvailableFaultType;

    @WebMethod(action = "cancelReservation")
    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.CancelReservationResponse")
    public void cancelReservation(

        @WebParam(name = "vehicleId", targetNamespace = "")
        java.lang.String vehicleId,
        @WebParam(name = "stationId", targetNamespace = "")
        java.lang.String stationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "success", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.Boolean> success,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "")
        jakarta.xml.ws.Holder<java.lang.String> message
    ) throws StationNotExistsFaultType, VehicleNotFoundFaultType, VehicleNotAvailableFaultType;

    @WebMethod(action = "getVehicles")
    @RequestWrapper(localName = "getVehicles", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.GetVehicles")
    @ResponseWrapper(localName = "getVehiclesResponse", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.GetVehiclesResponse")
    @WebResult(name = "vehicles", targetNamespace = "")
    public java.util.List<java.lang.String> getVehicles(

        @WebParam(name = "availableOnly", targetNamespace = "")
        boolean availableOnly,
        @WebParam(name = "stationId", targetNamespace = "")
        java.lang.String stationId
    ) throws StationNotExistsFaultType;

    @WebMethod(action = "getStationByVehicleId")
    @RequestWrapper(localName = "getStationByVehicleId", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.GetStationByVehicleId")
    @ResponseWrapper(localName = "getStationByVehicleIdResponse", targetNamespace = "http://acmemobility.org/station.xsd", className = "org.acmemobility.station.GetStationByVehicleIdResponse")
    @WebResult(name = "stationId", targetNamespace = "")
    public java.lang.String getStationByVehicleId(

        @WebParam(name = "vehicleId", targetNamespace = "")
        java.lang.String vehicleId
    ) throws VehicleNotFoundFaultType;
}
