
package org.acmemobility.station_wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2026-06-24T20:51:47.280+02:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "StationNotExistsFaultType", targetNamespace = "http://acmemobility.org/station.xsd")
public class StationNotExistsFaultType extends Exception {

    private org.acmemobility.station.StationNotExistsFaultType faultInfo;

    public StationNotExistsFaultType() {
        super();
    }

    public StationNotExistsFaultType(String message) {
        super(message);
    }

    public StationNotExistsFaultType(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public StationNotExistsFaultType(String message, org.acmemobility.station.StationNotExistsFaultType stationNotExistsFaultType) {
        super(message);
        this.faultInfo = stationNotExistsFaultType;
    }

    public StationNotExistsFaultType(String message, org.acmemobility.station.StationNotExistsFaultType stationNotExistsFaultType, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = stationNotExistsFaultType;
    }

    public org.acmemobility.station.StationNotExistsFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
