
package org.acmemobility.station_wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2026-06-24T20:51:47.342+02:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "VehicleNotFoundFaultType", targetNamespace = "http://acmemobility.org/station.xsd")
public class VehicleNotFoundFaultType extends Exception {

    private org.acmemobility.station.VehicleNotFoundFaultType faultInfo;

    public VehicleNotFoundFaultType() {
        super();
    }

    public VehicleNotFoundFaultType(String message) {
        super(message);
    }

    public VehicleNotFoundFaultType(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VehicleNotFoundFaultType(String message, org.acmemobility.station.VehicleNotFoundFaultType vehicleNotFoundFaultType) {
        super(message);
        this.faultInfo = vehicleNotFoundFaultType;
    }

    public VehicleNotFoundFaultType(String message, org.acmemobility.station.VehicleNotFoundFaultType vehicleNotFoundFaultType, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vehicleNotFoundFaultType;
    }

    public org.acmemobility.station.VehicleNotFoundFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
