
package org.acmemobility.station_wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2026-06-24T20:51:47.358+02:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "VehicleNotAvailableFaultType", targetNamespace = "http://acmemobility.org/station.xsd")
public class VehicleNotAvailableFaultType extends Exception {

    private org.acmemobility.station.VehicleNotAvailableFaultType faultInfo;

    public VehicleNotAvailableFaultType() {
        super();
    }

    public VehicleNotAvailableFaultType(String message) {
        super(message);
    }

    public VehicleNotAvailableFaultType(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public VehicleNotAvailableFaultType(String message, org.acmemobility.station.VehicleNotAvailableFaultType vehicleNotAvailableFaultType) {
        super(message);
        this.faultInfo = vehicleNotAvailableFaultType;
    }

    public VehicleNotAvailableFaultType(String message, org.acmemobility.station.VehicleNotAvailableFaultType vehicleNotAvailableFaultType, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = vehicleNotAvailableFaultType;
    }

    public org.acmemobility.station.VehicleNotAvailableFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
